node {
  stage 'build in development'
  openshiftBuild(namespace: 'dev-stage', buildConfig: 'welcome', showBuildLogs: 'true')
  
  stage 'deploy in development'
  openshiftDeploy(namespace: 'dev-stage', deploymentConfig: 'welcome')
  openshiftTag(namespace: 'dev-stage', sourceStream: 'welcome',  sourceTag: 'latest', destinationStream: 'welcome', destinationTag: 'promoteToQA', destinationNamespace: 'dev')

  stage 'deploy in QA'
  openshiftDeploy(namespace: 'qa-stage', deploymentConfig: 'welcome')

  stage 'scale dev and QA'
  openshiftScale(namespace: 'dev-stage', deploymentConfig: 'welcome',replicaCount: '2')
  openshiftScale(namespace: 'qa-stage', deploymentConfig: 'welcome',replicaCount: '3')
}
