node {
  stage 'build in development'
  openshiftBuild(namespace: 'app-dev', buildConfig: 'apps', showBuildLogs: 'true')
  
  stage 'deploy in development'
  openshiftDeploy(namespace: 'app-dev', deploymentConfig: 'apps')
  openshiftTag(namespace: 'app-dev', sourceStream: 'apps',  sourceTag: 'latest', destinationStream: 'apps', destinationTag: 'promoteToQA', destinationNamespace: 'app-dev')

  stage 'deploy in QA'
  openshiftDeploy(namespace: 'app-dev', deploymentConfig: 'apps')

  stage 'scale dev and QA'
  openshiftScale(namespace: 'app-dev', deploymentConfig: 'apps',replicaCount: '2')
  openshiftScale(namespace: 'app-dev', deploymentConfig: 'apps',replicaCount: '3')
}
